// Code generated by interfacer; DO NOT EDIT

package mockapi

import (
	"context"
	"github.com/sensu/sensu-go/api/core/v2"
)

// AssetClient is an interface generated for "github.com/sensu/sensu-go/backend/api.AssetClient".
type AssetClient interface {
	CreateAsset(context.Context, *v2.Asset) error
	FetchAsset(context.Context, string) (*v2.Asset, error)
	ListAssets(context.Context) ([]*v2.Asset, error)
	UpdateAsset(context.Context, *v2.Asset) error
}
