// Code generated by interfacer; DO NOT EDIT

package mockapi

import (
	"context"
	"github.com/sensu/sensu-go/api/core/v2"
)

// UserClient is an interface generated for "github.com/sensu/sensu-go/backend/api.UserClient".
type UserClient interface {
	CreateUser(context.Context, *v2.User) error
	DeleteUser(context.Context, string) error
	FetchUser(context.Context, string) (*v2.User, error)
	ListUsers(context.Context) ([]*v2.User, error)
	UpdateUser(context.Context, *v2.User) error
}
