---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
    attributes:
