#!/bin/sh
GOOS=linux GOARCH=amd64 COMPONENT=backend PACKAGE_TYPE=rpm SERVICE_TYPE=sysvinit
GOOS=linux GOARCH=amd64 COMPONENT=backend PACKAGE_TYPE=rpm SERVICE_TYPE=systemd
GOOS=linux GOARCH=i386 COMPONENT=backend PACKAGE_TYPE=rpm SERVICE_TYPE=sysvinit
GOOS=linux GOARCH=i386 COMPONENT=backend PACKAGE_TYPE=rpm SERVICE_TYPE=systemd
