name: static-check

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  staticcheck:
    name: staticcheck (project)
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.26.6
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v7
        with:
          go-version: "1.26.6"
      - uses: dominikh/staticcheck-action@v1.4.1
        with:
          version: "2025.1.1"
          install-go: false
          cache-key: "1.26.6"
env:
  GO_VERSION: 1.26.6
